### ISSUE TITLE
The urlparse module is renamed to urllib.parse in Python 3

### ISSUE THREAD

**Issue by mingalsuo** [FriendCode/gittle#49]
Hi!

Apparently Gittle has atleast this one issue with Python 3:

```
ImportError: No module named 'urlparse'
```

My environment:

```
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:45:13) [MSC v.1600 64 bit (AMD64)] on win32
```

According to https://docs.python.org/2/library/urlparse.html:

```
The urlparse module is renamed to urllib.parse in Python 3.
```

**Comment by gclsoft** [comment]
Me too,help

**Comment by alex-mac** [comment]
I'm not sure if this will solve your error, but you can try stepping into the code where the line is and just change urlparse to urllib.parse

**Comment by AFAgarap** [comment]
@mingalsuo was right.

@gclsoft The `urlparse` in Python 2.7.11 was renamed to `urllib.parse` in Python 3.
So, if you have a code such `from urlparse import urljoin`, I suggest you change it to `from urllib.parse import urljoin`

**Comment by lufeihaidao** [comment]
Same problem:

``` python
>>> from gittle import Gittle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/haidao/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/gittle/__init__.py", line 1, in <module>
    from . import utils
  File "/Users/haidao/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/gittle/utils/__init__.py", line 1, in <module>
    from . import paths, urls, git
  File "/Users/haidao/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/gittle/utils/urls.py", line 2, in <module>
    from urlparse import urlparse
ImportError: No module named 'urlparse'
```

And shell works fine.

**Comment by Thulebona** [comment]
open terminal nav to project or file dir and 

>  run  ` $ 2to3 -w projecname/` change the whole project to python3 

> or  ` $ 2to3 -w file.py` to change only one file

**Comment by forresthopkinsa** [comment]
I thought this was an issue because 2to3 didn't fix Urlparse?

**Comment by Thulebona** [comment]
2to3 works like a charm for me, haven't faced  any problems using it

**Comment by forresthopkinsa** [comment]
In that case, this issue should absolutely be closed; it's not a Gittle bug at all.

**Comment by KDIncognito** [comment]
What if you wanted to install `urllib.parse`? I was trying to install this module through windows `cmd` and all I get is one error message:    
```
Could not find a version that satisfies the requirement urllib.parse (from versions:)
No matching distribution found for urllib.parse
```
I tried alternative nomenclature as suggested here: http://python3porting.com/stdlib.html

**Comment by hammerofdawn** [comment]
Sreekrishnadutta,
urllib3 has the parse module, for windows cmd:
```
C:\>pip install urllib3
Collecting urllib3
   Using cached urllib3-1.20-py2.py3-none-any.whl
Installing collected packes: urllib3
Successfully installed urllib3-1.20
C:\>python
...
>>>from urllib import parse
```

Hope that helps

**Comment by coolrb** [comment]
> run $ 2to3 -w projecname/ change the whole project to python3
Worked like a charm for me, was struggling with geography project. It solved

**Comment by dheerajmpai** [comment]
Use `import urllib.parse as urlparse`

**Comment by madux** [comment]
Or simply use from urllib.parse import urlparse
