### ISSUE TITLE
Could I use gittle when the git repository is encrypted

### ISSUE THREAD

**Issue by sanjinjj** [FriendCode/gittle#58]
The git repository I used is encrypted, so the url likes 'ssh://username@company:port/projectname'.

I am trying to use gittle for my git repository, the code as below:

from gittle import Gittle
repo_path = 'D:\Git\projectname'
repo_url = 'ssh://username@company:port/projectname'
repo = Gittle.clone(repo_url,repo_path)

The error as below:
Traceback (most recent call last):
  File "D:\software\Java-workstation\git\try2.py", line 31, in <module>
    repo = Gittle.clone(repo_url,repo_path)
  File "C:\Python27\lib\site-packages\gittle\gittle.py", line 440, in clone
    repo.fetch(bare=bare)
  File "C:\Python27\lib\site-packages\gittle\gittle.py", line 407, in fetch
    remote_refs = self.fetch_remote(origin_uri)
  File "C:\Python27\lib\site-packages\gittle\gittle.py", line 364, in fetch_remote
    client, remote_path = self.get_client(origin_uri=origin_uri)
  File "C:\Python27\lib\site-packages\gittle\gittle.py", line 328, in get_client
    client, remote_path = get_transport_and_path(origin_uri, **client_kwargs)
  File "C:\Python27\lib\site-packages\dulwich\client.py", line 1125, in get_transport_and_path
    user_host, path = location.split(':')
ValueError: too many values to unpack

And it would work fine if I modified the repo_url as below:

from gittle import Gittle
repo_path = 'D:\Git\projectname'
repo_url = 'https://github.com/FriendCode/gittle.git'
repo = Gittle.clone(repo_url,repo_path)

Does this mean I cannot use gittle for git repository that is encrypted? Thanks.

**Comment by jelmer** [comment]
On Wed, Jan 07, 2015 at 12:15:55AM -0800, sanjinjj wrote:
> The git repository I used is encrypted, so the url likes 'ssh://username@company:port/projectname'.
the "ssh://" URL scheme doesn't mean that the repository is encrypted, just
that the connection to the remote server is.

> I am trying to use gittle for my git repository, the code as below:
> 
> from gittle import Gittle
> repo_path = 'D:\Git\projectname'
> repo_url = 'ssh://username@company:port/projectname'
Try git+ssh://username@cpmpany:port/projectname.

(replacing ssh: with git+ssh:)

Jelmer
