### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by c61811** [FriendCode/gittle#62]
>>> from gittle import Gittle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/gittle-0.5.0-py2.6.egg/gittle/__init__.py", line 1, in <module>
    from . import utils
  File "/usr/lib/python2.6/site-packages/gittle-0.5.0-py2.6.egg/gittle/utils/__init__.py", line 1, in <module>
    from . import paths, urls, git
  File "/usr/lib/python2.6/site-packages/gittle-0.5.0-py2.6.egg/gittle/utils/git.py", line 243
    for oldkey, newkey in key_pairs
      ^
SyntaxError: invalid syntax

**Comment by c2xbrhdj6u4qs15** [comment]
Hi,

I am getting the same error. Can somebody help?

>>> import gittle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/gittle/__init__.py", line 1, in <module>
    from . import utils
  File "/usr/lib/python2.6/site-packages/gittle/utils/__init__.py", line 1, in <module>
    from . import paths, urls, git
  File "/usr/lib/python2.6/site-packages/gittle/utils/git.py", line 243
    for oldkey, newkey in key_pairs
      ^
SyntaxError: invalid syntax

Thanks
