### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by Thor77** [FriendCode/gittle#63]
Gittle doesn't work at all with Python3, it would be very nice to get it working because its the best-looking git-libary for python i found so far.

**Comment by minhoryang** [comment]
+1

**Comment by hanbeibei** [comment]
+1

**Comment by eefret** [comment]
+1

**Comment by fusion44** [comment]
+1

**Comment by forresthopkinsa** [comment]
+1

**Comment by powellc** [comment]
@forresthopkinsa opened pull request 84 with a few elementary steps undertaken. Mostly I just updated the setup.py to pull in up to date requirements and ran 2to3 over the project.

There's still some work to do, though as it stands it works in the project I use it for.

**Comment by powellc** [comment]
I'll also note, that until this project is updated properly, I've created gittle3 and pushed it to PyPI. So if your project needs gittle with Py3 support, try pip install gittle3.

I will happily demote that fork when this project is updated.

**Comment by VeeeneX** [comment]
I've tried to test it, but I ran to an error: `TypeError: a bytes-like object is required, not 'str'`

Code:

``` python3
from gittle import Gittle

repo_path = '/tmp/1gittle_bare'
repo_url = 'git://github.com/FriendCode/gittle.git'

repo = Gittle.clone(repo_url, repo_path)
```

Error

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    repo = Gittle.clone(repo_url, repo_path)
  File "/usr/local/lib/python3.5/dist-packages/gittle/gittle.py", line 457, in clone
    local_repo = cls.init(local_path)
  File "/usr/local/lib/python3.5/dist-packages/gittle/gittle.py", line 312, in init
    repo = constructor(path)
  File "/usr/local/lib/python3.5/dist-packages/dulwich/repo.py", line 885, in init
    cls._init_maybe_bare(controldir, False)
  File "/usr/local/lib/python3.5/dist-packages/dulwich/repo.py", line 869, in _init_maybe_bare
    ret.refs.set_symbolic_ref("HEAD", "refs/heads/master")
  File "/usr/local/lib/python3.5/dist-packages/dulwich/refs.py", line 545, in set_symbolic_ref
    f.write(SYMREF + other + '\n')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by forresthopkinsa** [comment]
@VeeeneX

Does it still throw that error when cloning from a local repo? The error
doesn't quite make sense; it seems to be that something went wrong in the
Gittle-Dulwich interface, because Gittle.clone certainly does require a
string... Right?

But try changing the arguments and see if it still throws it.

**Comment by VeeeneX** [comment]
@forresthopkinsa  Problem is with dependency gittle3 uses old Dulwich 0.9.7, which has 'wb' flag for opening files for python2

**Comment by jelmer** [comment]
Dulwich is expecting bytes for most arguments, including ref names. This is
because Git is encoding-agnostic. Gittle is passing in a <str> object, which in
Python2 was a bytestring, but is a unicode string in Python 3.

**Comment by forresthopkinsa** [comment]
Ah, that makes sense. Thanks guys

**Comment by VeeeneX** [comment]
So, is there some workaround?

**Comment by forresthopkinsa** [comment]
Specify a bytestring rather than a normal string in the Dulwich interface?
Is that it?

**Comment by jelmer** [comment]
Yep, specifying a bytestring should be sufficient.

**Comment by AaronO** [comment]
I welcome and would happily merge a PR to add Python3 support.

**Comment by Thor77** [comment]
Great, will start working on that, if noone else wants to take it 👍

**Comment by forresthopkinsa** [comment]
@Thor77 The last commit, based on @powellc 's PR, is the result of a 2to3 and some configuration. Start from there.
