### ISSUE TITLE
在windows下使用 gittle.switch_branch 报错

### ISSUE THREAD

**Issue by khlipeng** [FriendCode/gittle#76]
我在windows下使用 switch_branch 切换分支报错，在Mac下正常~

1136 def clean(self, force=None, directories=None):
1137 untracked_files = self.untracked_files
-> 1138 map(os.remove, untracked_files)
1139 return untracked_files
1140 :
This is the error:
      WindowsError: [Error 3] : u'.git\\refs\\remotes\\origin\\v1.0'

**Comment by hanleilei** [comment]
Hay dude, English, Please describe your question in English...

**Comment by khlipeng** [comment]
I use the switch branch branch_switching error at windows, Apple under normal ~

**Comment by zhaoyc1990** [comment]
me too;

> > > repo.switch_branch('dev')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "build\bdist.win-amd64\egg\gittle\gittle.py", line 1185, in switch_branch

  File "build\bdist.win-amd64\egg\gittle\gittle.py", line 1207, in clean_working

  File "build\bdist.win-amd64\egg\gittle\gittle.py", line 1200, in clean
WindowsError: [Error 32] : '.git\objects\pack\pack-aa48931cc1e1008153ac757bed
84aae75478fa9b.pack'
