### ISSUE TITLE
push when authenticating with username/password

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [FriendCode/gittle#78]
When I try to push with username and password, I get the following error:
```
Traceback (most recent call last):
  File "/Users/luke/Desktop/pythonista-cloud/index.py", line 37, in <module>
    pushFile("index.py")
  File "/Users/luke/Desktop/pythonista-cloud/index.py", line 35, in pushFile
    repo.push()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gittle/gittle.py", line 343, in push
    return self.push_to(origin_uri, branch_name, progress)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gittle/gittle.py", line 333, in push_to
    client, remote_path = self.get_client(origin_uri)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gittle/gittle.py", line 328, in get_client
    client, remote_path = get_transport_and_path(origin_uri, **client_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dulwich/client.py", line 1105, in get_transport_and_path
    return get_transport_and_path_from_url(location, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dulwich/client.py", line 1086, in get_transport_and_path_from_url
    **kwargs), parsed.path
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dulwich/client.py", line 932, in __init__
    GitClient.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'username'
```

**Comment by zangsir** [comment]
I have the exact same error when pushing with username and password.

**Comment by sephib** [comment]
I'm running on Windows and having the same error. did you manage to solve this issue?
